name: blowgun
description: A Dart port for gunjs
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.2 <3.0.0'


dependencies:
  web_socket_channel: ^2.1.0
  shelf_web_socket: ^1.0.1
  shelf: ^1.3.0
  equatable: ^2.0.3
  json_annotation: ^4.4.0
  uuid: ^3.0.6
  rxdart: ^0.27.3

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0
